#!/bin/sh

echo "Creating an RDF representation of all SOMEF repos found in data/somef/oeg_json. Results are stored in results_somef_rdf-star. Remember to start the environment for morph-star first!"


# Requirements: morph-kgc (with the star version)
# input folder: folder with all JSONs generated by SOMEF.
# output folder: folder where all .nt files of the transformations will be placed.
# all_repos.nt: file aggregating all RDF files.
folder=data/somef/oeg_json
results_folder=results_somef_rdf-star
mkdir $results_folder
line_n=0
for entry in "$folder"/*
do
  echo "Processing: $entry"
  entry_name=$(basename "$entry")
  cp $entry data/somef/file_to_process.json
  python3 -m morph_kgc configuration_somef.ini
  cp output/0-0-0-0.nt results_somef_rdf-star/"$entry_name"_.nt
done
cat results_somef_rdf-star/*.nt > all_repos.nt
